name: Build and Release Foundry Module

on:
  push:
    tags:
      - 'v*' # Trigger the workflow only when a version tag (e.g., v1.0.0) is pushed

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a ZIP file with the specified files
      - name: Create ZIP
        run: |
          mkdir -p dist/gurps-negative-hp
          cp module.json dist/gurps-negative-hp/
          cp scripts/gurps-negative-hp.js dist/gurps-negative-hp/
          cd dist
          zip -r module.zip gurps-negative-hp

      # Create a GitHub Release and upload the ZIP file
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/module.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes
            Automated release for version ${{ github.ref_name }}.
          draft: false
